import { Inter } from 'next/font/google';
import './globals.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import "@fortawesome/fontawesome-svg-core/styles.css";

import Navbar from '../components/Navbar';

config.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Recipe App',
  description: 'Generated by Jantje Treffers',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='flex flex-wrap h-100'>
          <Navbar />
        </div>
        <div className='flex-grow overflow-y-auto bg-pageColor max-w-7xl mx-auto'>
          {children}
        </div>
      </body>
    </html>
  );
}
